"eslint-config-gabe":
  - packages/eslint-config/*
  - packages/eslint-config/**/*

"tsconfig-gabe":
  - packages/tsconfig/*
  - packages/tsconfig/**/*

"tm-cl":
  - packages/tm-cl/*
  - packages/tm-cl/**/*

enhancement:
  - src/*
  - src/**/*

test:
  - "**/*.spec.*"

ci:
  - .github/workflows/*
  - .github/labeler.yml

docs:
  - apps/docs/*
  - apps/docs/**/*
  - .github/docs/*
  - .github/docs/**/*
  - "**/README.md"
